name: "fast_wiki"
mode: "dev"
port: "8088"
version: "v0.0.1"
startTime: "2023-03-21"
MachineID: 1
log:
  level: "debug"
  filename: "web_app.log"
  errfilename: "web_app_err.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "fastwiki"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: "6379"
  password: "ljy123"
  db: 0
  pool_size: 100
elasticSearch:
  host: "http://127.0.0.1:9200"